config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'staticpages#top'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'
  # asをつかうことで、images_ogp_pathのヘルパーを使うことができる。resourceなどは自動でヘルパーを生成してくれる。
  # OGPのルーティング

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  ## 設定したprepare_meta_tagsをprivateにあってもpostコントローラー以外にも使えるようにする
  helper_method :prepare_meta_tags

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    ## メタタグを設定する。
    prepare_meta_tags(@post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :image)
  end

  def prepare_meta_tags(post)
    ## OGP画像を取得するためのURLを構築（MiniMagickで生成される画像のエンドポイント）
    ## このURLにアクセスすると、/images/ogp.png にルーティングされ、OGP画像が動的に生成される
    image_url = "#{request.base_url}/images/ogp.png?text=#{CGI.escape(post.title)}"

    # setset_meta_tags は、meta-tags gem によって提供されるメソッドで、メタタグを簡潔に設定できます。
    # og:は Facebook、LinkedIn、Pinterest、Discord などのOGP対応SNSで使用される設定。
    set_meta_tags(
      title: 'まーちゃん',
      discription: 'まーちゃん大学ごめんね学部',
      og: {
        site_name: 'サイトの名前',
        title: post.title,
        description: '投稿の説明',
        type: 'website',
        url: request.original_url,
        image: image_url,
        locale: 'ja-JP'
      },
      # twitter:は Twitter のシェアプレビュー用設定
      twitter: {
        card: 'summary_large_image',
        site: '@gshota_0116',
        image: image_url
      }
    )
    # 　上記image: image_urlを表示するために、/images/ogp.pngにアクセスがいき、ogpアクションが走る！
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

    <p>
    <strong>Imgae:</strong>
    <%= image_tag  post.image.url if post.image? %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>

  <div class="text-gray-600">
    <%# prepare_meta_tags @post %> <%# prepare_meta_tags @post は、メタタグを設定するメソッドですが、showアクションで既に呼び出されているため、ここでは不要かも。要確認 %>
    <%#twitter_share_urlはtwitterが提供する機能%>
    <% twitter_share_url = "https://twitter.com/share?url=#{CGI.escape(post_url(@post))}" %> <%#post_urlにしないと完全なURLにならない %>
  <%= link_to twitter_share_url, target: '_blank', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded", title: "Xでシェア" do %>
    <span>Share on X</span>
  <% end %>
  </div>
</div>